### PR TITLE
fix php deprecated warning when passing null as subject in preg_match()

### LINKED ISSUE #876: Deprecated notice php 8.1
php 8.1 gives

preg_match(): Passing null to parameter #2 ($subject) of type string is deprecated on line 1460 in /httpdocs/vendor/mobiledetect/mobiledetectlib/Mobile_Detect.php

### PR DESCRIPTION
**Pull request by julienbornstein**
fix #876

### CODE REVIEW

File: Mobile_Detect.php [hunk 1]
```diff
@@ -1450,13 +1450,17 @@ public function is($key, $userAgent = null, $httpHeaders = null)
...
      * @param $regex
-     * @param  string $userAgent
+     * @param string $userAgent
      * @return bool
      *
      * @todo: search in the HTTP headers too.
      */
     public function match($regex, $userAgent = null)
     {
+        if (!\is_string($userAgent) && !\is_string($this->userAgent)) {
```
Comment (serbanghita) [inline Mobile_Detect.php:1460]: @julienbornstein thank you! 👍 Are the qualifiers really required since they are build in methods?

Comment (julienbornstein) [reply Mobile_Detect.php:1460]: sorry @serbanghita  I'm not sure to understand your question ? can you be more specific ?

Comment (serbanghita) [reply Mobile_Detect.php:1460]: @julienbornstein I was refering to the usage of `\is_string` instead of `is_string`

Comment (julienbornstein) [reply Mobile_Detect.php:1460]: oh I see, it's to avoid collision if another is_string() function is declared. I'm not sure it's usefull herebut it's an habit that I have ... you can remove them if you want. 

Stackoverflow: [Should I use a backslah before global functions in PHP even if is not needed?](https://stackoverflow.com/questions/62568683/should-i-use-a-backslah-before-global-functions-in-php-even-if-is-not-needed)

**Comment by JayBizzle** [comment]
Hi @serbanghita

Any chance you could tag a new release with this fix please. Our deprecation logs are filling up very quickly because of this.

Thanks 👍🏻

**Comment by serbanghita** [comment]
@JayBizzle yes, doing it today

**Comment by JayBizzle** [comment]
Brilliant, thank you
